# This file was generated by GoReleaser. DO NOT EDIT.
cask "ask" do
  name "ask"
  desc "A thin CLI wrapper around Claude Code for fast, single-shot queries"
  homepage "https://github.com/laurensent/ask"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ask"

  on_macos do
    on_intel do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "57de113dab3d0b0f6978bd0a31e3ebedd0b9fe82f035705261eb4dc43b7877ee"
    end
    on_arm do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "615da7f96402cbb57f80e1a314cfd9c104f6919c377f5150cf5f91664cab34a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_linux_amd64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "e2ade59ecbf46256f3c5836bc746449208891e19f2d412e1c5f24942d889a470"
    end
    on_arm do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_linux_arm64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "50a5f9d425ef843285a530885078b61c725e60d0739760dd6eb89f85802d7a9f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ask"]
    end
  end

  # No zap stanza required
end
