# This file was generated by GoReleaser. DO NOT EDIT.
cask "ask" do
  name "ask"
  desc "A thin CLI wrapper around Claude Code for fast, single-shot queries"
  homepage "https://github.com/laurensent/ask"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ask"

  on_macos do
    on_intel do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "9d75f45d5d13e84eda1b8e84867fe6252e1155ad51a9f789a77dad1749d546b5"
    end
    on_arm do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "5230bb0829c088ed38794b26c9a22fc051c2e0500aa648c873a09c45338a7558"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_linux_amd64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "b15853498eae2948c948af8147c20a97bca05fb474c45c8e675fab819ec7ae76"
    end
    on_arm do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_linux_arm64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "3bf2333daa64049a883823e177ae87490ab6480a87f840edacfbe5cd66b466df"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ask"]
    end
  end

  # No zap stanza required
end
