# This file was generated by GoReleaser. DO NOT EDIT.
cask "ask" do
  name "ask"
  desc "A thin CLI wrapper around Claude Code for fast, single-shot queries"
  homepage "https://github.com/laurensent/ask"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ask"

  on_macos do
    on_intel do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "c1450f941d44ff63a835ce1c600e2db35f6b52b2f05e8fee1c5364c8ece1d00f"
    end
    on_arm do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "47a54505df8e71818b46a2688b8dd0dc8b80040e72c0db616f50891a561dcbdd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_linux_amd64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "2745900f9d8b4e755e3ae23acb74b77058be78396ae444056b4e61b555a27bbc"
    end
    on_arm do
      url "https://github.com/laurensent/ask/releases/download/v#{version}/ask_#{version}_linux_arm64.tar.gz",
        verified: "github.com/laurensent/ask"
      sha256 "ec4630e7fca001de064056e2cb427aeae0ecfbc938053e60a01edac1a50fa6df"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ask"]
    end
  end

  # No zap stanza required
end
