# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-query" do
  name "cc-query"
  desc "A thin CLI wrapper around Claude Code for fast, single-shot queries"
  homepage "https://github.com/laurensent/cc-query"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-query"

  on_macos do
    on_intel do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "42581394c9d244efcdb54c2b7523a04762700b49a387144162699c636ac851ec"
    end
    on_arm do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "214e6704c783838c680f5f0d405facae2164debe289d68949a2d218ed83b5790"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_linux_amd64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "5ac1311e9df0b4ae670c662487220230e81df48d73bbc022574af43ed811b2b5"
    end
    on_arm do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_linux_arm64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "6b7e1e27bfd3324c141e3f8a4976cd3f7dd46036b6d4a60b5c84c065d9bebfff"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-query"]
    end
  end

  # No zap stanza required
end
