# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-query" do
  name "cc-query"
  desc "A thin CLI wrapper around Claude Code for fast, single-shot queries"
  homepage "https://github.com/laurensent/cc-query"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-query"

  on_macos do
    on_intel do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "b476bc739a8c959a16c7d62e9b1363fe3c1d6ff9f2644da3fc1a0fa6807ece90"
    end
    on_arm do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "a24c698858873bfa6a276414c223a0a9bcfbf063eb8a9548028df6fd3d1a4743"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_linux_amd64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "4bfc82f871dcc847d49145131c22e84096194c070bbbf50bf0fa30dabbc0a2bd"
    end
    on_arm do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_linux_arm64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "73ce25f6299735c6c6e3a80499b8e14e4fcc4da09deee1738971eaeafebab409"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-query"]
    end
  end

  # No zap stanza required
end
