# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-query" do
  name "cc-query"
  desc "A thin CLI wrapper around Claude Code for fast, single-shot queries"
  homepage "https://github.com/laurensent/cc-query"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-query"

  on_macos do
    on_intel do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "d27b6f59db717d66161f49ab85e06c17d68a4f6eb762efb4518019fbab0c655e"
    end
    on_arm do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "67d459986cc4e205e3a58ebafc246fb95f4758a7d387c52399034912aa077377"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_linux_amd64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "a4632c9f28b66b7f14233aa3a6564cf1796a8fd599dbf1396c821cc46b47ef52"
    end
    on_arm do
      url "https://github.com/laurensent/cc-query/releases/download/v#{version}/cc-query_#{version}_linux_arm64.tar.gz",
        verified: "github.com/laurensent/cc-query"
      sha256 "d338ff2860ab658230d36d9a2e3d26b34c5b0fa3bb43369b2577cd9f523eab00"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-query"]
    end
  end

  # No zap stanza required
end
